version : "3.8"

services:
  frontendimg :
    build: /home/ubuntu/studentapp-3tier-docker-image/frontend                                                                   
    container_name: frontend
    ports:
    - "80:80"
    network_mode: bridge

  backendimg :
   build: /home/ubuntu/studentapp-3tier-docker-image/backend                                                                      
   container_name: backend
   ports:
   - "8080:8080"
   network_mode: bridge
   depends_on: 
   - "frontendimg"

 
