version : "3.8"

services:
  frontendimg :
    build: /home/ubuntu/var/lib/jenkins/workspace/studentapp2/frontend                                                                      
    container_name: frontend
    ports:
    - "9000:80"
    network_mode: bridge

  backendimg :
   build: /home/ubuntu/var/lib/jenkins/workspace/studentapp2/backend                                                                        
   container_name: backend
   ports:
   - "8080:8080"
   network_mode: bridge
   depends_on: 
   - "frontendimg"

 
